apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog-argo-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wibowoharianja94-rgb/deployment.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog-argo-cd
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true